# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

builds:
  - skip: true # ビルドはワークフローで実施するため

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  extra_files:
    - glob: ./i544cAutoWear-*.zip
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
